/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const DungeonLazyRouteImport = createFileRoute('/dungeon')()
const MuseumLazyRouteImport = createFileRoute('/museum')()
const OldOneLazyRouteImport = createFileRoute('/old-one')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DungeonLazyRoute = DungeonLazyRouteImport.update({
  id: '/dungeon',
  path: '/dungeon',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dungeon.lazy').then((d) => d.Route))
const MuseumLazyRoute = MuseumLazyRouteImport.update({
  id: '/museum',
  path: '/museum',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/museum.lazy').then((d) => d.Route))
const OldOneLazyRoute = OldOneLazyRouteImport.update({
  id: '/old-one',
  path: '/old-one',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/old-one.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dungeon': typeof DungeonLazyRoute
  '/museum': typeof MuseumLazyRoute
  '/old-one': typeof OldOneLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dungeon': typeof DungeonLazyRoute
  '/museum': typeof MuseumLazyRoute
  '/old-one': typeof OldOneLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/dungeon': typeof DungeonLazyRoute
  '/museum': typeof MuseumLazyRoute
  '/old-one': typeof OldOneLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dungeon' | '/museum' | '/old-one'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dungeon' | '/museum' | '/old-one'
  id: '__root__' | '/' | '/dungeon' | '/museum' | '/old-one'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DungeonLazyRoute: typeof DungeonLazyRoute
  MuseumLazyRoute: typeof MuseumLazyRoute
  OldOneLazyRoute: typeof OldOneLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeon': {
      id: '/dungeon'
      path: '/dungeon'
      fullPath: '/dungeon'
      preLoaderRoute: typeof DungeonLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museum': {
      id: '/museum'
      path: '/museum'
      fullPath: '/museum'
      preLoaderRoute: typeof MuseumLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old-one': {
      id: '/old-one'
      path: '/old-one'
      fullPath: '/old-one'
      preLoaderRoute: typeof OldOneLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DungeonLazyRoute: DungeonLazyRoute,
  MuseumLazyRoute: MuseumLazyRoute,
  OldOneLazyRoute: OldOneLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
