/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const ArtGalleryLazyRouteImport = createFileRoute('/art-gallery')()
const DungeonLazyRouteImport = createFileRoute('/dungeon')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ArtGalleryLazyRoute = ArtGalleryLazyRouteImport.update({
  id: '/art-gallery',
  path: '/art-gallery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/art-gallery.lazy').then((d) => d.Route))
const DungeonLazyRoute = DungeonLazyRouteImport.update({
  id: '/dungeon',
  path: '/dungeon',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dungeon.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/art-gallery': typeof ArtGalleryLazyRoute
  '/dungeon': typeof DungeonLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/art-gallery': typeof ArtGalleryLazyRoute
  '/dungeon': typeof DungeonLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/art-gallery': typeof ArtGalleryLazyRoute
  '/dungeon': typeof DungeonLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/art-gallery' | '/dungeon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/art-gallery' | '/dungeon'
  id: '__root__' | '/' | '/art-gallery' | '/dungeon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ArtGalleryLazyRoute: typeof ArtGalleryLazyRoute
  DungeonLazyRoute: typeof DungeonLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art-gallery': {
      id: '/art-gallery'
      path: '/art-gallery'
      fullPath: '/art-gallery'
      preLoaderRoute: typeof ArtGalleryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeon': {
      id: '/dungeon'
      path: '/dungeon'
      fullPath: '/dungeon'
      preLoaderRoute: typeof DungeonLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ArtGalleryLazyRoute: ArtGalleryLazyRoute,
  DungeonLazyRoute: DungeonLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
